services:
  db:
    container_name: web-shop-db
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: webshop
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5332:5432"
    restart: unless-stopped

volumes:
  postgres_data:
